### PR TITLE
Add french

### PR DESCRIPTION
**Pull request by LeoBenoist**

### CODE REVIEW

**Comment by amansilla** [comment]
Thanks for your contribution @LeoBenoist ! 😉

I've updated your PR's base branch to `2.X` since it's affected as well by your changes for later create a new PR to get your changes on the `master` branch for support Akeneo 3.0.

Please don't forget to 🌟 the repo if you like it!

**Comment by LeoBenoist** [comment]
Thanks :)

**Comment by amansilla** [comment]
Hi @LeoBenoist if it's not a problem for you create a PR adding your changes on the top of the `2.X` branch, since it's affected as well by your changes.

**Comment by LeoBenoist** [comment]
done https://github.com/flagbit/akeneo-product-cloner/pull/17

**Comment by amansilla** [comment]
This will be closed, since changes are applied by #17 and #18.

**Pull request closed without merging**
